import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Back from "../components/Back";
import Link from 'next/link'

export default function contact() {
  return (
    <>
       <Head>
        <title>SajidHanifApp - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <center>
        <br />
        <h2>Contact</h2>
        <br />
        <Back />
      </center>
      <main className={styles.main}>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/services">Services</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
          <Link href="/blog/[blog_slug].tsx">Blog</Link>
          </li>
          <li>
            <Link href="/gallery">Gallery</Link>
          </li>
        </ul>
        {/* <button onClick={() => router.back()}> */}
        {/* <h2>Back</h2>
        </button> */}
      </main>
    </>
  );
}
