import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Link from "next/link";
import { Header, Footer } from "../components/index";
import { useRef } from "react";

export default function Home() {
  // useFef Hook:
  const h1Ref = useRef<any>(null);
  console.log("h1Ref", h1Ref);

  return (
    <>
      <Head>
        <title>SajidHanifApp - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}> */}
        {/* <Header /> */}
        {/* useRef in h1 heading: */}
        <h1 ref={h1Ref}>Welcome to SajidHanifApp</h1>
        <Link href="/services">Services</Link>
        <Link href="/about">About</Link>
        <Link href="/contact">Contact</Link>
        <Link href="/blog">Blog</Link>
        {/* <Footer /> */}
        {/* </div> */}
      </main>
    </>
  );
}
