import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Counter, Todo } from "@/components";
import Back from "../components/Back";
import PushBack from "@/components/PushBack";
import Navbar from "../components/Navbar";

// import { useRouter } from "next/router"; // useRouter, remember its history and have "Back" method

export default function services() {
  // const router = useRouter(); // useRouter, remember its history and have "Back" method

  return (
    <>
      <Head>
        <title>SajidHanifApp - Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className={styles.main}> */}
      <Navbar
        title="SajidHanifApp"
        servicesText="Services"
        serviceOne="Counter App"
        serviceTwo="Todo List App"
        moreServices="More Services"
        aboutText="About"
        contactText="Contact"
        blogText="Blog"
        galleryText="Gallery"
      />
      <center>
        <h1 className="h1-color">Services</h1>
        <br />
        <Back />
        <br />
        <Counter />
        <br />
        <br />
        <Todo />
        <br />
        <h2 className="app-color">Visit to Gallery</h2>
        <PushBack />
        <br />
        <br />
        <br />
        <Link href="/">Home</Link>
        <br />
        <Link href="/about">About</Link>
        <br />
        <Link href="/contact">Contact</Link>
        <br />
        <Link href="/blog/[blog_slug].tsx">Blog</Link>
        <br />
        <Link href="/gallery">Gallery</Link>
        <br />
        <br />
      </center>
      {/* </main> */}
    </>
  );
}
